language: node_js
sudo: false
cache: yarn
node_js:
- '6.1'
script: yarn test && yarn build
deploy:
  provider: npm
  email: albert.fazullin@flatstack.com
  api_key:
    secure: DdEi35F3oQvSKLfUNlnJbBIu0N2iDUQfyosLUtnLAxIoEZzog0OGsBq+JI0Zx7nWG2LAuHQIfQf8Eim1+MafTL0OugXP02Gb4ogMQ1dBJrLmjNpH3bdwLLcK5sxQCyYdSdKGwzvd+MrDd4SOoNReJLdH7b5s15n+GFjYqEQp6NkcmDvDh5rxsz5uhgQLWnUuMErJFoEzEtDseI0nspOvP7eq+Se+IQdd81H08K3xuk+xW/DQPbX7gwHNnUs5J6Bmc7/sV7FrGxxWpbDc0CZf71pouK27unf3v6DRLo+3y8S2VsOm4ZOdruvbjGBSqIESoVysTc9N+Jt0D4PAOJCc4EVhBkRKFJdMdc4pY7IRbPyfk+GwJuY98rdi2Ti9Jd+h9rQjANbtK/CHNJzxVtuEiMgpdoHMQmDZL5Tp2u2kSX+k/pcxZlNQtAT7HD8fr0txjURleUhiQeK/HMcZEigdLrKAfg4TirfTzfRYsmu6WUYTRK46xKxjMciGzPX5J+u7CLGvob5oJ4UDLoYC+HeFPcgTVXWZxVtE0yhM0nTZ4cjoYu7OXk+O8xcTi4cwmlEcDNjg+VG/isB6PKMdBpQB922MKxV9EBv2DUNXwuAMfOImV23C82C0EvXatgBaimxHUlU3FwT7Yd6k9EFfE45uW7sY6Gq3SbMQBjTDwOKv6Yg=
  on:
    tags: true
    repo: AlbertFazullin/fs-jwt-xhr-hook
